export const GET_EMPLOYEELIST_REQUESTED = 'GET_EMPLOYEELIST_REQUESTED'
export const GET_EMPLOYEELIST_SUCCESS = 'GET_EMPLOYEELIST_SUCCESS'
export const GET_EMPLOYEELIST_FAILED = 'GET_EMPLOYEELIST_FAILED'
export const RESET_EMPLOYEELIST_REQUESTED = 'RESET_EMPLOYEELIST_REQUESTED'
